---
title: Это новый сайт
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
