---
title: Indexmod Encyclopedia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Indexmod (2006, Moscow) website on a concept which originates from the
  idea of wiki and statistics. It has realized in the poster supplied to Afisha magazine
  in Moscow in 2005. Later in 2006, Indexmod was established as brand of an experimental
  project about design and art. Today Indexmod developing as the wiki Indexmod Encyclopedia.
  The aim of the project is to create software based on the idea of an anonymous real-time
  wiki editing.
show_downloads: true
google_analytics: 'UA-111762431-1

'
theme: jekyll-theme-minimal
