---
title:
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
description: 
include: ['.htaccess']
show_sidebar: false
show_downloads: false
google_analytics: 'UA-111762431-1

'
theme: jekyll-theme-minimal
