---
title: Indexmod Encyclopedia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
description: Indexmod Encyclopedia — is an alternative wiki with pretty syntax

show_sidebar: false
show_downloads: false
show_title: false
show_description: false
google_analytics: ''

gems:
plugins:
  - jekyll-toc

theme: jekyll-theme-minimal
include: ['.htaccess']



