---
title: Tale
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day/:title"
paginate: 5
baseurl: "/tale"
url: https://chesterhow.github.io
sass:
  sass_dir: _sass
  style: :compressed
markdown: kramdown
author:
  name: Chester How
  url: http://chester.how
  email: chesterhow@gmail.com
version: 3.4.1
github:
  repo: https://github.com/chesterhow/tale
plugins:
- jekyll-paginate
