---
title: Indexmod Encyclopedia
timezone: Moscow
collections:
  uploads:
    title: Uploads
    output: true
  posts: 
    title: Posts
    output: true
description: git-wiki is a jekyll theme originally based on jekyll-theme-minimal
show_downloads: true 
git_branch: master
logo_url: 
google_analytics: 
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: false
google_cse_token: 
custom_head: true
custom_sidebar: true
custom_footer: true
gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-feed
