---
title: Indexmod Encyclopedia
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Hello! Hello...
show_downloads: true
git_branch: master
google_analytics: 
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: false
google_cse_token: 
custom_head: true
custom_sidebar: true
custom_footer: true
gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-feed
