---
title: Indexmod Encyclopedia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Indexmod (2006, Moscow) website and brand based a concept which originates
  from the idea of visualization of the statistics about fashion and artists. Firstly
  it has realized in the poster supplied to Afisha magazine in Moscow in 2005. Later
  in 2006, Indexmod was established as brand name covering an experimental project
  to arrange data about designers and artists. Today Indexmod developing as the wiki
  (Indexmod Encyclopedia) on the one hand, as rating engine (Indexmod) on the other
  hand. The aim of the project is to create an elegant looking, alternative software
  based on the idea of an anonymous real-time wiki editing and semantic markup integration.
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
