---
title: ABC
timezone: UTC
collections:
  posts:
    title: DEF
    output: true
  uploads:
    title: GHJ
    output: true
author: 
email: 
description: '123'
twitter_username: 
github_username: 
minima:
  date_format:
markdown: 
theme: minima
exclude:
- Gemfile
- Gemfile.lock
